[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

# Netlify Identity
[context.production.environment]
  NETLIFY_USE_YARN = "true"

# Criar usuário admin automaticamente
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Configuração do usuário admin
[context.production.environment]
  ADMIN_EMAIL = "angycalm@powerscrews.com"
  ADMIN_PASSWORD = "admin123456"

# Security headers (basic)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


