[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  ADMIN_EMAIL = "angycalm@powerscrews.com"
  ADMIN_PASSWORD = "admin123456"
  NETLIFY_IDENTITY_CONFIRM_EMAIL = "false"

# Security headers (basic)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


